// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Feed struct {
	ID            int32
	Name          string
	Url           string
	UserID        uuid.NullUUID
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	LastFetchedAt sql.NullTime
}

type FeedFollow struct {
	ID        int32
	UserID    uuid.NullUUID
	FeedID    sql.NullInt32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Post struct {
	ID          int32
	Title       string
	Url         string
	Description string
	FeedID      sql.NullInt32
	PublishedAt sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type User struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
